### ISSUE TITLE
Regular crashes

### ISSUE THREAD

**Issue by fsteff** [RangerMauve/datmobile#2]
I just tried the playstore release on a Xiaomi Mi Note 5 and got the following crash log:

> com.facebook.react.common.JavascriptException: Socket is not connected., stack:
> _write@829:4911
> w@398:1756
> _@398:2726
> v@398:2156
> onwrite@398:731
> <unknown>@829:5319
> value@55:3738
> <unknown>@55:1282
> value@55:2703
> value@55:1252
>     at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
>     at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
>     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
>     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>     at android.os.Handler.handleCallback(Handler.java:794)
>     at android.os.Handler.dispatchMessage(Handler.java:99)
>     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
>     at android.os.Looper.loop(Looper.java:176)
>     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
>     at java.lang.Thread.run(Thread.java:764)

**Comment by RangerMauve** [comment]
Thanks for the report! I'm currently working on getting all the rendering into a WebView. I'll see what I can do about this instability after I get that running.
